eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway

# Product Service Routes
  cloud:
    gateway:
      mvc:
        routes[0]:
          id: product-service
          uri: lb://product-service
          predicates[0]: Path=/api/product

# Order Service Routes
        routes[1]:
          id: order-service
          uri: lb://order-service
          predicates[0]: Path=/api/order

# Inventory Service Routes
        routes[2]:
          id: inventory-service
          uri: lb://inventory-service
          predicates[0]: Path=/api/inventory

# Discovery Server Routes
        routes[3]:
          id: discovery-server
          uri: http://localhost:8761
          predicates[0]: Path=/eureka/web
          filters[0]: SetPath=/

# Discovery Server Static Resource Routes
        routes[4]:
          id: discovery-server-static
          uri: http://localhost:8761
          predicates[0]: Path=/eureka/**

# Spring Security

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8480/realms/ecommerce

# Distributed Tracing

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

  tracing:
    sampling:
      probability: 1.0

# Logging

logging:
  level:
    root: info
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionLocator: info

    org.springframework.cloud.gateway: TRACE



server:
  port: 8380



