spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order-service?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: order-service

# Jpa properties

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

# Cloud properties

  cloud:
    compatibility-verifier:
      enabled: false

# Kafka properties

  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: notificationTopic
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.ecommerce.orderservice.event.OrderPlacedEvent

server:
  port: 8180

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#management:
#  health:
#    circuitbreakers:
#      enabled: true
#
#  endpoint:
#    health:
#      show-details: always

## Resiliance 4j circuitbreaker properties
#
#resilience4j:
#  circuitbreaker:
#    instances:
#      inventory:
#        register-health-indicator: true      # To able to see the state of the Circuitbreaker in Console
#        event-consumer-buffer-size: 10       # How many events can be stored in the buffer
#        sliding-window-type: COUNT_BASED     # On what basis the circuitbreaker will be opened
#        sliding-window-size: 5               # After how many failed requests the circuitbreaker will be opened
#        failure-rate-threshold: 50           # If the failure rate is greater than 50% the circuitbreaker will be opened
#        wait-duration-in-open-state: 5s      # How much time to wait in open state
#        permitted-number-of-calls-in-half-open-state: 3 # How many calls can be made in half open state
#        automatic-transition-from-open-to-half-open-enabled: true # To enable automatic transition from open to half open
#

