spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory-service?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: inventory-service

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

server:
  port: 8280

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka